CLASS ZBP_R_SALESORDERTP DEFINITION
  PUBLIC
  FOR BEHAVIOR OF ZR_SALESORDERTP .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_SALESORDERTP IMPLEMENTATION.
ENDCLASS.
